# Generated by Django 2.2 on 2019-08-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_fod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fod',
            new_name='Food',
        ),
    ]
