# Generated by Django 2.2 on 2019-10-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20191007_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.Base', verbose_name='所属拠点'),
        ),
        migrations.AlterField(
            model_name='base',
            name='image',
            field=models.ImageField(blank=True, upload_to='base_image', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='base',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='拠点名(英語)'),
        ),
        migrations.AlterField(
            model_name='base',
            name='name_ja',
            field=models.CharField(max_length=100, unique=True, verbose_name='拠点名(日本語)'),
        ),
        migrations.AlterField(
            model_name='base',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='拠点コード'),
        ),
    ]
