# Generated by Django 2.2 on 2019-08-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20190826_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
    ]
